name: Terraform Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 👇 STEP: Zip JobFailureOrSuccessAlertsLambda
      - name: Zip JobFailureOrSuccessAlertsLambda
        run: |
          cd JobFailureOrSuccessJob
          zip -r JobFailureOrSuccessAlertsLambda.zip . -x "*.zip"
          cd ..

      # 👇 STEP: Zip test-lambda-trigger
      - name: Zip test-lambda-trigger
        run: |
          cd Test-Trigger-Lambda
          zip -r test-lambda-trigger.zip . -x "*.zip"
          cd ..

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
